### ISSUE TITLE
Cant load extension

### ISSUE THREAD

**Issue by Teenspirit** [arenatemp/stable-diffusion-webui-model-toolkit#16]
Hello, I'm having trouble loading the extension. I get the following error:

> Error loading script: toolkit_gui.py
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui-master\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\StableDiffusion\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\StableDiffusion\stable-diffusion-webui-master\extensions\stable-diffusion-webui-model-toolkit\scripts\toolkit_gui.py", line 13, in <module>
    VAE_SAVE_PATH = shared.cmd_opts.vae_dir or os.path.join("models", "VAE")
AttributeError: 'Namespace' object has no attribute 'vae_dir'

Appreciate any help

**Comment by arenatemp** [comment]
see https://github.com/arenatemp/stable-diffusion-webui-model-toolkit/issues/5
