### ISSUE TITLE
[Feature Request] Ability to convert all files from a folder

### ISSUE THREAD

**Issue by Nacurutu** [arenatemp/stable-diffusion-webui-model-toolkit#20]
Hi, I would like to know if there is the possibility of adding an option to convert all files inside a folder directly instead of having to select one by one

Im downloading a lot of models lately and I would love to tell the extension to look for all the files inside a folder and start converting them one by one automatically...

Is this possible?

Also, with a progress bar? :) 

Many thanks for considering my request. I love this extension, it saves a lot of space on my drive

**Comment by arenasys** [comment]
Added this feature in b8638ae5247892e832fc97a267cc7171ba7620cf. No fancy GUI for now. See the [readme](https://github.com/arenatemp/stable-diffusion-webui-model-toolkit#autopruning) for info.

**Comment by Nacurutu** [comment]
Thank you very much, will give it a try later... a lot of work right now....

**Comment by Nacurutu** [comment]
Im getting 2 errors:

As I have a different models path assigned to a different drive in my webUI Arguments, I get this error if I left the argument in the bat file:

```
Exception in thread Thread-80 (autoprune):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-model-toolkit\scripts\toolkit_gui.py", line 732, in autoprune
    in_model = os.path.relpath(in_model, os.path.abspath("."))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 747, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'D:', start on mount 'C:'
```
Removing the path from the bat file, it started to work.


However, for the first 5 files it worked properly but then I started to get these errors:

```
PRUNING models\Autoprune\dra2_10.safetensors
        DETECTED AS SD-v1
        MOVING TO models\Stable-diffusion\dra2_10.safetensors
Exception in thread Thread-80 (autoprune):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-model-toolkit\scripts\toolkit_gui.py", line 768, in autoprune
    os.remove(in_model)
PermissionError: [WinError 5] Access is denied: 'models\\Autoprune\\dra2_10.safetensors'
```

**Comment by arenasys** [comment]
The autoprune path is now relative to the `--ckpt-dir` path if its set. Not sure why its failing to `os.remove` (safetensors shenanigans im guessing) but im ignoring that error now, so you may need to manually delete leftover models.

**Comment by Nacurutu** [comment]
> The autoprune path is now relative to the `--ckpt-dir` path if its set. Not sure why its failing to `os.remove` (safetensors shenanigans im guessing) but im ignoring that error now, so you may need to manually delete leftover models.

Thank you for adding the --ckpt-dir

Regarding the other error, the autoprune just stops after the error, so the prune is not made. I also don't know why, I don't understand too much about coding, sorry for not being a great help on that.

**Comment by arenasys** [comment]
That error isnt fatal anymore, it will save the pruned model and continue, just the old model will be left over in the autoprune folder.

**Comment by Nacurutu** [comment]
> That error isnt fatal anymore, it will save the pruned model and continue, just the old model will be left over in the autoprune folder.

Thanks bro.. u rock..!!!
