### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by 2x-y** [arenatemp/stable-diffusion-webui-model-toolkit#21]
I updated the repo today and I'm now getting an error when launching Automatic1111:

Error loading script: toolkit_gui.py
Traceback (most recent call last):
  File "D:\GitHub\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\GitHub\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\GitHub\stable-diffusion-webui\extensions\stable-diffusion-webui-model-toolkit\scripts\toolkit_gui.py", line 777, in <module>
    if shared.opts.model_toolkit_autoprune:
  File "D:\GitHub\stable-diffusion-webui\modules\shared.py", line 533, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'model_toolkit_autoprune'

**Comment by arenasys** [comment]
oops. fixed in 8a97290f2fd14a5bd38a10807e39b27c048223e7
