### ISSUE TITLE
AttributeError: 'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by HomegrownExplorer** [arenatemp/stable-diffusion-webui-model-toolkit#31]
Getting this error a lot - granted I did put everything in the Autoprune (Lora/VAE/Models/Hypernetworks) 

been moving the error causing files out as it happens, but its happened on Models and Hypernetworks so far.

Exception:

Exception in thread Thread-126 (autoprune):
Traceback (most recent call last):
  File "C:\Users\A-Desktop\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\A-Desktop\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "L:\AI Business\GitHub Repositories\automatic\extensions\stable-diffusion-webui-model-toolkit\scripts\toolkit_gui.py", line 778, in autoprune
    fix_model(model, fix_clip=shared.opts.model_toolkit_fix_clip)
  File "L:\AI Business\GitHub Repositories\automatic\extensions\stable-diffusion-webui-model-toolkit\toolkit.py", line 562, in fix_model
    if k.startswith(r):
AttributeError: 'int' object has no attribute 'startswith'

**Comment by arenasys** [comment]
fixed the error, but hypernetworks are not supported so wont be pruned
