### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'vae_dir'

### ISSUE THREAD

**Issue by Testertime** [arenatemp/stable-diffusion-webui-model-toolkit#5]
This error prevents the extension from loading. Full log is:

```
Reloading extensions
Reloading custom scripts
Error loading script: toolkit_gui.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "F:\stable-diffusion-webui\extensions\stable-diffusion-webui-model-toolkit\scripts\toolkit_gui.py", line 12, in <module>
    VAE_SAVE_PATH = shared.cmd_opts.vae_dir or os.path.join("models", "VAE")
AttributeError: 'Namespace' object has no attribute 'vae_dir'

Reloading modules: modules.ui
Refreshing Model List
Restarting Gradio
Running on local URL:  http://127.0.0.1:7860
```
My Stable Diffusion web UI installation has vae folders and such, so I don't know what is going on here.

Thank you for looking into this.

**Comment by arenasys** [comment]
your webui needs to be updated, the vae dir arg was added a few days ago in https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/6e08da2c315c346225aa834017f4e32cfc0de200
